### ISSUE TITLE
Open PRs dont show Policy status

### ISSUE THREAD

**Issue by erendrake** [BertCotton/TfsAdvanced#6]
Currently the open PR view looks like 

![image](https://cloud.githubusercontent.com/assets/486486/19734817/3e7a720e-9b66-11e6-81a5-ee355dce6d7b.png)

It would be nice to know not only if a potential merge has conflicts. But a summary of policies that are either passing or failing on the PR like we do in the VSTS overview

![image](https://cloud.githubusercontent.com/assets/486486/19734862/76d98ae0-9b66-11e6-9c77-65d72351e059.png)

**Comment by BertCotton** [comment]
This is difficult because the api for PullRequests does not expose the policy rules.

To do this the work flow will need to be as follows:
1) Get the polocies for project (https://{instance}/defaultcollection/{project}/_apis/policy/configurations)
2) Find the policy for the merge target branch (compar configuration.settings.scope.refName == pullrequest.targetRefName)
3) look into the settings and check for the settings (ie. minimumApproverCount == count of number of reviewers who have approved the PR)

This would be a nice feature to have, but will be a bit more expensive.

**Comment by BertCotton** [comment]
@erendrake please verify.

**Comment by erendrake** [comment]
This looks great! Thanks!
